{% set name = "distfit" %}
{% set version = "1.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/distfit-{{ version }}.tar.gz
  sha256: df4047f9923ea4152134a766b84a9c30fddbf73bbd8c77d22d25d29e8ace5ae8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - matplotlib-base >=3.5.2
    - packaging
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - packaging
    - matplotlib-base >=3.5.2
    - numpy
    - pandas
    - statsmodels
    - scipy
    - pypickle
    - colourmap >=1.1.10
    - joblib

test:
  imports:
    - distfit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/erdogant/distfit
  summary: Probability density function fitting and hypothesis testing.
  license: MIT
  license_file: LICENSE
  description: |
    Distfit is a python package for probability density fitting across
     89 univariate distributions to non-censored data by residual sum of
     squares (RSS), and hypothesis testing. Probability density fitting
     is the fitting of a probability distribution to a series of data
     concerning the repeated measurement of a variable phenomenon.
     Distfit scores each of the 89 different distributions for the fit
     with the empirical distribution and return the best scoring
     distribution.

extra:
  recipe-maintainers:
    - thewchan
