{% set name = "distfit" %}
{% set version = "1.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/distfit-{{ version }}.tar.gz
  sha256: 99ad18cdca728b4e02e0c67273bed966bc16fd14c8ea7f7936bba9f6dbdbb615

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - matplotlib-base >=3.5.2
    - numpy
    - pandas
    - statsmodels
    - scipy
    - pypickle >=1.1.4
    - colourmap >=1.1.10
    - packaging
    - joblib

test:
  imports:
    - distfit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/erdogant/distfit
  summary: Probability density function fitting and hypothesis testing.
  license: MIT
  license_file: LICENSE
  description: |
    Distfit is a python package for probability density fitting across
     89 univariate distributions to non-censored data by residual sum of
     squares (RSS), and hypothesis testing. Probability density fitting
     is the fitting of a probability distribution to a series of data
     concerning the repeated measurement of a variable phenomenon.
     Distfit scores each of the 89 different distributions for the fit
     with the empirical distribution and return the best scoring
     distribution.

extra:
  recipe-maintainers:
    - thewchan
